# https://travis-ci.org/denis-peshkov/VirtualRrouterManager
language: csharp
solution: VirtualRouterManager.sln
script:
  - grep "Test Results" build.log
install:
#  - sudo apt-get install nunit-console
  - nuget restore VirtualRouterManager.sln
#  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release VirtualRouterManager.sln
#  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/62031f782e1d7f3d28e1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always